// <auto-generated />
using System;
using GRDL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GRDL.Migrations
{
    [DbContext(typeof(GRDBContext))]
    [Migration("20210315045959_RenamedTableLOL")]
    partial class RenamedTableLOL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("GRModels.Cart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationID")
                        .HasColumnType("integer");

                    b.Property<int>("localID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("LocationID");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("GRModels.CartProduct", b =>
                {
                    b.Property<int>("CartID")
                        .HasColumnType("integer");

                    b.Property<int>("RecID")
                        .HasColumnType("integer");

                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<int>("RecQuan")
                        .HasColumnType("integer");

                    b.HasKey("CartID", "RecID");

                    b.HasIndex("RecID");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("GRModels.Customer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<int>("ZipCode")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("GRModels.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("localName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GRModels.LocationProduct", b =>
                {
                    b.Property<int>("LocID")
                        .HasColumnType("integer");

                    b.Property<int>("RecID")
                        .HasColumnType("integer");

                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<int>("RecQuan")
                        .HasColumnType("integer");

                    b.HasKey("LocID", "RecID");

                    b.ToTable("LocationProducts");
                });

            modelBuilder.Entity("GRModels.Order", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CartID")
                        .HasColumnType("integer");

                    b.Property<int>("CusID")
                        .HasColumnType("integer");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("integer");

                    b.Property<int>("LocalID")
                        .HasColumnType("integer");

                    b.Property<int?>("LocationID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("TotalCoast")
                        .HasColumnType("numeric");

                    b.HasKey("ID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("LocationID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("GRModels.OrderProduct", b =>
                {
                    b.Property<int>("OrdID")
                        .HasColumnType("integer");

                    b.Property<int>("RecID")
                        .HasColumnType("integer");

                    b.Property<int>("ID")
                        .HasColumnType("integer");

                    b.Property<int>("RecQuan")
                        .HasColumnType("integer");

                    b.HasKey("OrdID", "RecID");

                    b.HasIndex("RecID");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("GRModels.Record", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<int>("DaCondition")
                        .HasColumnType("integer");

                    b.Property<int>("DaFormat")
                        .HasColumnType("integer");

                    b.Property<int>("GenreType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("RecordName")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Records");

                    b.HasData(
                        new
                        {
                            ID = 1000,
                            Artist = "Noname",
                            DaCondition = 1,
                            DaFormat = 1,
                            GenreType = 1,
                            Price = 249.99m,
                            RecordName = "Telefone"
                        });
                });

            modelBuilder.Entity("GRModels.Cart", b =>
                {
                    b.HasOne("GRModels.Customer", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRModels.Location", "Location")
                        .WithMany("Carts")
                        .HasForeignKey("LocationID");

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GRModels.CartProduct", b =>
                {
                    b.HasOne("GRModels.Cart", "Cart")
                        .WithMany("CartProducts")
                        .HasForeignKey("CartID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRModels.Record", "Record")
                        .WithMany("CartProducts")
                        .HasForeignKey("RecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("GRModels.LocationProduct", b =>
                {
                    b.HasOne("GRModels.Location", "Location")
                        .WithMany("LocationProducts")
                        .HasForeignKey("LocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRModels.Record", "Record")
                        .WithMany("LocationProducts")
                        .HasForeignKey("LocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("GRModels.Order", b =>
                {
                    b.HasOne("GRModels.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("GRModels.Location", "Location")
                        .WithMany("Orders")
                        .HasForeignKey("LocationID");

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("GRModels.OrderProduct", b =>
                {
                    b.HasOne("GRModels.Order", "Order")
                        .WithMany("OrderProducts")
                        .HasForeignKey("OrdID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GRModels.Record", "Record")
                        .WithMany("OrderProducts")
                        .HasForeignKey("RecID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("GRModels.Cart", b =>
                {
                    b.Navigation("CartProducts");
                });

            modelBuilder.Entity("GRModels.Customer", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GRModels.Location", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("LocationProducts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("GRModels.Order", b =>
                {
                    b.Navigation("OrderProducts");
                });

            modelBuilder.Entity("GRModels.Record", b =>
                {
                    b.Navigation("CartProducts");

                    b.Navigation("LocationProducts");

                    b.Navigation("OrderProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
